### ISSUE TITLE
Question: Data sources

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [estevanmaito/windmill-dashboard-react#2]
What data sources does this dashboard support?

**Comment by estevanmaito** [comment]
Could you clarify what do you mean by _support for data sources_?

Take [Tables.js](https://github.com/estevanmaito/windmill-dashboard-react/blob/master/src/pages/Tables.js) as an example. You can attach whatever data you want, you just need to fetch it and place it in the right place.

**Comment by affluent-bilby-classifieds** [comment]
Does it work with Simple REST or a JSON server for example?

**Comment by estevanmaito** [comment]
Yes, it does. Tables page is a great example of external data being used.

Closing for now, but feel free to continue the discussion.
