### ISSUE TITLE
IPad like sized Displays Responsive "Issue"

### ISSUE THREAD

**Issue by TimmKroe** [estevanmaito/windmill-dashboard-react#3]
`windmill-dashboard-react` version: `0.3.1`

### What you did:

I simply started putting content in.

### What happened:

![Bildschirmfoto am 2020-07-22 um 17 57 09](https://user-images.githubusercontent.com/27803956/88199363-0e1fdb80-cc45-11ea-8d96-01efa418c1d8.png)

### Reproduction:

Simple open Dev Tools and select the IPad Preset

### Problem description:

On IPad Like Displays the Sidebar Menu is still the Desktop.
https://windmill-dashboard-react.vercel.app/app/dashboard

### Suggested solution:

It would be awesome if the Sidebar on IPad sized screens would be hidden.

**Comment by estevanmaito** [comment]
Thank you for following the issue template 🙏 

I agree it is better to show the sidebar only on larger screens.

This is now available on `0.4.0`. [Changelog explains the changes](https://github.com/estevanmaito/windmill-dashboard-react/blob/master/CHANGELOG.md#breaking-changes).
