### ISSUE TITLE
Error when setting up new routes 

### ISSUE THREAD

**Issue by sgr0691** [estevanmaito/windmill-dashboard-react#6]
I've encountered a problem when creating new pages and routing them. I read and followed the instructions in the documentation about Routes. I'm not sure what to do with this error.

The error I keep receiving is " ./src/routes/index.js , Line 25:1:  Parsing error: Unexpected token, expected "," " 

`const routes = [`
`{ path: '/dashboard', // the url`
`component: Dashboard, // view rendered`

**Comment by estevanmaito** [comment]
Closing for not using the issue template.

Update this issue with the template, or create a new one filling the information needed.

![Screenshot_2020-09-06 estevanmaito windmill-dashboard-react](https://user-images.githubusercontent.com/8527573/92337522-b9171800-f080-11ea-9a4f-3587e0307724.png)
