### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by jamesofoaye** [estevanmaito/windmill-dashboard-react#7]
`windmill-dashboard-react` version: ``

### Relevant code or config:

```html
<!-- your code here -->
```

### What you did:
i tried running npm start when i cloned the project

### What happened:
The Application didn't start
[2020-09-18T11_37_08_200Z-debug.log](https://github.com/estevanmaito/windmill-dashboard-react/files/5245893/2020-09-18T11_37_08_200Z-debug.log)
![issue](https://user-images.githubusercontent.com/58654469/93604989-b20fd400-f9b5-11ea-9f37-cb5aa269d382.png)

**Comment by estevanmaito** [comment]
The answer is already in the `WARN` lines: you should install (`npm install`) before you try to run other commands.

Run `npm install` and then you'll be able to `npm start`.

**Comment by jamesofoaye** [comment]
Thanks It running now… Sent from Mail for Windows 10 From: Estevan MaitoSent: Friday, September 18, 2020 4:05 PMTo: estevanmaito/windmill-dashboard-reactCc: James Ofori Ayerakwa; AuthorSubject: Re: [estevanmaito/windmill-dashboard-react] npm start issue (#7) The answer is already in the WARN lines: you should install (npm install) before you try to run other commands.Run npm install and then you'll be able to npm start.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
